version: 2.1

jobs:
    test-e2e:
        macos:
            xcode: '14.2.0'
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: Run e2e test
                  command: ./scripts/run-e2e-tests.sh

    build:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout
            - run:
                  name: install node
                  command: npm install
            - run:
                  name: check node version
                  command: node -v

workflows:
    test_my_app:
        jobs:
            - build
            - test-e2e:
                  requires:
                      - build
