version: 2.1
# orbs:
#     cypress: cypress-io/cypress@3

jobs:
    test-e2e:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout
            - run:
                  name: Install package
                  command: npm install
            - run:
                  name: Install dependency
                  command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            - run:
                  name: Run e2e tests
                  command: bash ./scripts/run-e2e-tests.sh
            - store_artifacts:
                  path: /tmp/e2e-videos/

workflows:
    test-build:
        jobs:
            # test only
            - test-e2e
