version: 2.1
# orbs:
#     cypress: cypress-io/cypress@3

jobs:
    test-e2e:
        docker:
            - image: cimg/node:15.1
        steps:
            - checkout
            - run:
                  name: Run e2e tests
                  command: bash ./scripts/run-e2e-tests.sh
            - store_artifacts:
                  path: /tmp/e2e-videos/

workflows:
    test-build:
        jobs:
            # test only
            - test-e2e
